# Design Description 

# Analytical Questions 

### 1. Are there any property features that make a house more popular for purchase and where are they located? 
### 2. Do these popular property features differ by county?
### 3. Are there any underlying relationships between these housing features and its locations?


* Questions 1,2,3 may be answered with geolocation plot that uses coloured dots to represent the continuous housing feature such as price, total square feet, and price per square feet. These three variables show interesting trends such as the general transaction are happening in central Los Angeles on houses below the 1 million dollar threshold. However, we do see interesting trends such as the price per square feet in downtown Los Angeles is actually not that expensive and there also seems to be a cluster around the LA Palmdale Regional Airport that seems to have big properties with low cost per square feet.

* This plot may be made even more interactive by including a slider or clicker that can the change the housing features being plotted, this way we can answer the questions by observing all the different housing features.

* The alternative to a geolocation plot will be a chloropleth map coloured by county. This may result in losing the pin point location of the transactions, which is why I won't be using this



### 4. Where are the transactions located and what type of properties are people buying?
### 5. What are the high volume of transaction months through out the year? 

* Question 4 and 5 can be answered with a simple bar plot that is stacked with the number of transactions in each county.

* The second part of question 4 where we find the type of properties can be answered with either pie charts or bar plots

* We can also create 12 pie charts representing the months and use the size of the pie charts to represent the total volumne of transactions and the percentages inside show where the transactions are located. This may not be as practical for visualizing. 

### 3. Does the year built of the property affect the purchase of these houses? 
* I plotted one line chart that indicates the supply and demand of houses in the market based on the year built. We can see the people tend to buy houses from 1940s to present. I also used Zillow's estimate to show that there exists fluctuations and very volatile housing prices from the houses built in 1800s to 1940s.

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline 

df = pd.read_csv("properties_2016.csv")

/Users/chi/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning:

Columns (22,32,34,49,55) have mixed types. Specify dtype option on import or set low_memory=False.

# Cleaning the Data

In [57]:
df.head()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2015.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,650756.0,1413387.0,2015.0,762631.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,7.0,NaN,NaN,...,1.0,NaN,571346.0,1156834.0,2015.0,585488.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,NaN,NaN,193796.0,433491.0,2015.0,239695.0,5725.17,NaN,NaN,NaN

# Look at the missing ratio in the variables

In [58]:
# construct missing ratio 
df_na = df.isnull().sum()*100/len(df)
df_na = df_na.drop(df_na[df_na ==0].index).sort_values(ascending =False)
#len(df_na) # =34
df_na # this is seen as the missing data ratio in the predictor variables

storytypeid                     99.945599
basementsqft                    99.945465
yardbuildingsqft26              99.911330
fireplaceflag                   99.827048
architecturalstyletypeid        99.796966
typeconstructiontypeid          99.773986
finishedsquarefeet13            99.743000
buildingclasstypeid             99.576949
decktypeid                      99.427311
finishedsquarefeet6             99.263002
poolsizesum                     99.063385
pooltypeid2                     98.925539
pooltypeid10                    98.762603
taxdelinquencyflag              98.108613
taxdelinquencyyear              98.108546
hashottuborspa                  97.688141
yardbuildingsqft17              97.308236
finishedsquarefeet15            93.608572
finishedsquarefeet50            93.209304
finishedfloor1squarefeet        93.209304
threequarterbathnbr             89.560859
fireplacecnt                    89.527160
pooltypeid7                     83.737899
poolcnt                         82.663438
numberofstories                 77.151778
airconditioningtypeid           72.815410
garagecarcnt                    70.411967
garagetotalsqft                 70.411967
regionidneighborhood            61.262381
heatingorsystemtypeid           39.488453
buildingqualitytypeid           35.063749
unitcnt                         33.757244
propertyzoningdesc              33.719090
lotsizesquarefeet                9.248875
finishedsquarefeet12             9.246664
calculatedbathnbr                4.318346
fullbathcnt                      4.318346
censustractandblock              2.516601
landtaxvaluedollarcnt            2.268947
regionidcity                     2.105207
yearbuilt                        2.007492
calculatedfinishedsquarefeet     1.861339
structuretaxvaluedollarcnt       1.841809
taxvaluedollarcnt                1.425357
taxamount                        1.046825
regionidzip                      0.468308
propertycountylandusecode        0.411260
roomcnt                          0.384394
bathroomcnt                      0.383959
bedroomcnt                       0.383557
assessmentyear                   0.383188
propertylandusetypeid            0.383121
fips                             0.383121
regionidcounty                   0.383121
latitude                         0.383121
longitude                        0.383121
rawcensustractandblock           0.383121
dtype: float64

A lot of these variable have a high missing ratio lets look into each and see what the reason is and what we can do 
* storytypeid: this is the type of floors probably not important (remove)
* basementsqft: most likely no basement so (fill with 0) 
* yardbuildingsqft26: this is most likely because there is no storage shed in yard so ill just remove it (remove)
* fireplaceflag: no fire place so just remove this column (Remove)
* architecturalstyletypeid: no style record (remove)
* typeconstructiontypeid: not recorded (remove)
* finishedsquarefeet13: perimeter living area probably not recorded as well (remove)
* buildingclasstypeid: similar reasons as above (remove)
* decktypeid: similar reasons as above  (remove)
* finishedsquarefeet6: similar reasons as above (remove)
* poolsizesum: no pool fill with 0 
* pooltypeid2: similar reasons as above (remove)
* pooltypeid10: similar reasons as above (remove)
* taxdelinquencyflag: replace with 0 
* taxdelinquencyyear: similar reasons as above (remove)
* hashottuborspa: similar reasons as above (remove)
* yardbuildingsqft17: similar reasons as above (remove)
* finishedsquarefeet15: similar reasons as above (remove)
* finishedsquarefeet50: similar reasons as above (remove)
* finishedfloor1squarefeet: similar reasons as above (remove)
* threequarterbathnbr:similar reasons as above (remove)
* fireplacecnt: replace with 0
* pooltypeid7: similar reasons as above (remove)
* poolcnt: replace with 0
* numberofstories: 0
* airconditioningtypeid: similar reasons as above (remove)
* garagecarcnt: replace with 0
* garagetotalsqft: since no garage no measurement of square feet => replace with 0
* regionidneighborhood: similar reasons as above (remove)

In [59]:
df = df.drop(["storytypeid"], axis = 1)

In [60]:
df = df.drop(["yardbuildingsqft26"], axis = 1)
df = df.drop(["fireplaceflag"], axis = 1)
df = df.drop(["architecturalstyletypeid"], axis = 1)
df = df.drop(["typeconstructiontypeid"], axis = 1)
df = df.drop(["finishedsquarefeet13"], axis = 1)
df = df.drop(["buildingclasstypeid"], axis = 1)
df = df.drop(["decktypeid"], axis = 1)
df = df.drop(["finishedsquarefeet6"], axis = 1)
df = df.drop(["pooltypeid2"], axis = 1)
df = df.drop(["pooltypeid10"], axis = 1)
df = df.drop(["hashottuborspa"], axis = 1)
df = df.drop(["taxdelinquencyyear"], axis = 1)
df = df.drop(["yardbuildingsqft17"], axis = 1)
df = df.drop(["finishedsquarefeet15"], axis = 1)
df = df.drop(["finishedsquarefeet50"], axis = 1)
df = df.drop(["finishedfloor1squarefeet"], axis = 1)
df = df.drop(["threequarterbathnbr"], axis = 1)
df = df.drop(["pooltypeid7"], axis = 1)
df = df.drop(["airconditioningtypeid"], axis = 1)
df = df.drop(["regionidneighborhood"], axis = 1)

In [61]:
df = df.drop(["poolsizesum"], axis = 1)

In [62]:
# construct missing ratio 
df_na = df.isnull().sum()*100/len(df)
df_na = df_na.drop(df_na[df_na ==0].index).sort_values(ascending =False)
#len(df_na) # =34
df_na # this is seen as the missing data ratio in the predictor variables

basementsqft                    99.945465
taxdelinquencyflag              98.108613
fireplacecnt                    89.527160
poolcnt                         82.663438
numberofstories                 77.151778
garagecarcnt                    70.411967
garagetotalsqft                 70.411967
heatingorsystemtypeid           39.488453
buildingqualitytypeid           35.063749
unitcnt                         33.757244
propertyzoningdesc              33.719090
lotsizesquarefeet                9.248875
finishedsquarefeet12             9.246664
calculatedbathnbr                4.318346
fullbathcnt                      4.318346
censustractandblock              2.516601
landtaxvaluedollarcnt            2.268947
regionidcity                     2.105207
yearbuilt                        2.007492
calculatedfinishedsquarefeet     1.861339
structuretaxvaluedollarcnt       1.841809
taxvaluedollarcnt                1.425357
taxamount                        1.046825
regionidzip                      0.468308
propertycountylandusecode        0.411260
roomcnt                          0.384394
bathroomcnt                      0.383959
bedroomcnt                       0.383557
assessmentyear                   0.383188
rawcensustractandblock           0.383121
fips                             0.383121
latitude                         0.383121
longitude                        0.383121
regionidcounty                   0.383121
propertylandusetypeid            0.383121
dtype: float64

In [63]:
# replace with 0's 
df["basementsqft"] = df["basementsqft"].fillna(0)

df["taxdelinquencyflag"] = df["taxdelinquencyflag"].fillna(0)

df["fireplacecnt"] = df["fireplacecnt"].fillna(0)

df["poolcnt"] = df["poolcnt"].fillna(0)

df["numberofstories"] = df["numberofstories"].fillna(0)

df["garagecarcnt"] = df["garagecarcnt"].fillna(0)


df["garagetotalsqft"] = df["garagetotalsqft"].fillna(0)

df["unitcnt"] = df["unitcnt"].fillna(0) #meaning only 1 unit

In [64]:
# construct missing ratio 
df_na = df.isnull().sum()*100/len(df)
df_na = df_na.drop(df_na[df_na ==0].index).sort_values(ascending =False)
#len(df_na) # =34
df_na # this is seen as the missing data ratio in the predictor variables

heatingorsystemtypeid           39.488453
buildingqualitytypeid           35.063749
propertyzoningdesc              33.719090
lotsizesquarefeet                9.248875
finishedsquarefeet12             9.246664
calculatedbathnbr                4.318346
fullbathcnt                      4.318346
censustractandblock              2.516601
landtaxvaluedollarcnt            2.268947
regionidcity                     2.105207
yearbuilt                        2.007492
calculatedfinishedsquarefeet     1.861339
structuretaxvaluedollarcnt       1.841809
taxvaluedollarcnt                1.425357
taxamount                        1.046825
regionidzip                      0.468308
propertycountylandusecode        0.411260
roomcnt                          0.384394
bathroomcnt                      0.383959
bedroomcnt                       0.383557
assessmentyear                   0.383188
latitude                         0.383121
fips                             0.383121
longitude                        0.383121
rawcensustractandblock           0.383121
regionidcounty                   0.383121
propertylandusetypeid            0.383121
dtype: float64

In [65]:
df["heatingorsystemtypeid"] = df["heatingorsystemtypeid"].fillna("None")
#Probably no heating fill with None

In [66]:
df["buildingqualitytypeid"] = df["buildingqualitytypeid"].fillna("None")
#probably not recorded but quality may be important so lets just put none for the empty records

In [67]:
df["propertyzoningdesc"] = df["propertyzoningdesc"].fillna("None")

In [68]:
df = df.dropna(subset=['lotsizesquarefeet'], axis = 0)
#since I want every house to have a lot size

In [69]:
df = df.dropna(subset=['finishedsquarefeet12'], axis = 0)

In [70]:
#lets just drop "calculatedbathnbr" since we have bathroomcnt
df = df.drop(["calculatedbathnbr"], axis = 1)

In [71]:
df = df.drop(["fullbathcnt"], axis = 1)

In [72]:
# construct missing ratio 
df_na = df.isnull().sum()*100/len(df)
df_na = df_na.drop(df_na[df_na ==0].index).sort_values(ascending =False)
#len(df_na) # =34
df_na # this is seen as the missing data ratio in the predictor variables

regionidcity                  1.723699
censustractandblock           0.229231
taxamount                     0.097954
structuretaxvaluedollarcnt    0.079241
yearbuilt                     0.073808
regionidzip                   0.030425
landtaxvaluedollarcnt         0.005594
taxvaluedollarcnt             0.005513
roomcnt                       0.000322
bedroomcnt                    0.000161
bathroomcnt                   0.000161
dtype: float64

In [73]:
#lets not fill in any regionidcity by median so just drop rows that lacks regiondicity
df = df.dropna(subset=['regionidcity'], axis = 0)
#as well as censustractandblock
df = df.dropna(subset=['censustractandblock'], axis = 0)

In [74]:
df = df.dropna(subset=['taxvaluedollarcnt'], axis = 0)
df = df.dropna(subset=['landtaxvaluedollarcnt'], axis = 0)
df = df.dropna(subset=['structuretaxvaluedollarcnt'], axis = 0)
df = df.dropna(subset=['taxamount'], axis = 0)

In [75]:
# construct missing ratio 
df_na = df.isnull().sum()*100/len(df)
df_na = df_na.drop(df_na[df_na ==0].index).sort_values(ascending =False)
#len(df_na) # =34
df_na

yearbuilt      0.071474
regionidzip    0.004724
dtype: float64

In [76]:
df = df.dropna(subset=['yearbuilt'], axis = 0)
df = df.dropna(subset=['regionidzip'], axis = 0)

In [77]:
df.head(10)

,parcelid,basementsqft,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedfinishedsquarefeet,finishedsquarefeet12,fips,fireplacecnt,garagecarcnt,...,unitcnt,yearbuilt,numberofstories,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,censustractandblock
295,17051828,0.0,4.0,4.0,None,4969.0,4969.0,6111.0,3.0,4.0,...,0.0,1989.0,1.0,768000.0,2195000.0,2015.0,1427000.0,24389.58,0,6.111001e+13
296,17052152,0.0,2.0,3.0,None,1800.0,1800.0,6111.0,0.0,2.0,...,0.0,1932.0,2.0,315000.0,783000.0,2015.0,468000.0,8516.04,0,6.111001e+13
297,17052992,0.0,1.0,2.0,None,780.0,780.0,6111.0,1.0,2.0,...,0.0,1971.0,1.0,69177.0,87400.0,2015.0,18223.0,1633.28,0,6.111001e+13
298,17053038,0.0,2.0,2.0,None,1250.0,1250.0,6111.0,0.0,2.0,...,0.0,1978.0,1.0,78381.0,229920.0,2015.0,151539.0,3162.08,0,6.111001e+13
299,17053061,0.0,1.0,2.0,None,1404.0,1404.0,6111.0,2.0,1.0,...,0.0,1950.0,1.0,98354.0,309132.0,2015.0,210778.0,3951.70,0,6.111001e+13
300,17053543,0.0,2.0,3.0,None,1505.0,1505.0,6111.0,1.0,2.0,...,0.0,1961.0,1.0,297853.0,595706.0,2015.0,297853.0,7164.86,0,6.111001e+13
301,17054185,0.0,2.0,3.0,None,1181.0,1181.0,6111.0,0.0,2.0,...,0.0,1961.0,1.0,43812.0,60087.0,2015.0,16275.0,1268.58,0,6.111001e+13
302,17054285,0.0,3.0,4.0,None,2025.0,2025.0,6111.0,2.0,2.0,...,0.0,1961.0,1.0,222083.0,444166.0,2015.0,222083.0,5488.46,0,6.111001e+13
303,17054331,0.0,2.5,4.0,None,1620.0,1620.0,6111.0,1.0,2.0,...,0.0,1967.0,2.0,218351.0,363915.0,2015.0,145564.0,4546.78,0,6.111001e+13
304,17054431,0.0,2.5,3.0,None,2148.0,2148.0,6111.0,1.0,2.0,...,0.0,1981.0,1.0,197372.0,292166.0,2015.0,94794.0,3773.62,0,6.111001e+13

In [78]:
len(df.columns)
#we still have 34 variables to use after cleaning
print(df.columns)

Index(['parcelid', 'basementsqft', 'bathroomcnt', 'bedroomcnt',
       'buildingqualitytypeid', 'calculatedfinishedsquarefeet',
       'finishedsquarefeet12', 'fips', 'fireplacecnt', 'garagecarcnt',
       'garagetotalsqft', 'heatingorsystemtypeid', 'latitude', 'longitude',
       'lotsizesquarefeet', 'poolcnt', 'propertycountylandusecode',
       'propertylandusetypeid', 'propertyzoningdesc', 'rawcensustractandblock',
       'regionidcity', 'regionidcounty', 'regionidzip', 'roomcnt', 'unitcnt',
       'yearbuilt', 'numberofstories', 'structuretaxvaluedollarcnt',
       'taxvaluedollarcnt', 'assessmentyear', 'landtaxvaluedollarcnt',
       'taxamount', 'taxdelinquencyflag', 'censustractandblock'],
      dtype='object')

In [79]:
#check the dtype to see if anything must be changed
for t in df.columns:
    print(t+': '+str(df[t].dtype))

parcelid: int64
basementsqft: float64
bathroomcnt: float64
bedroomcnt: float64
buildingqualitytypeid: object
calculatedfinishedsquarefeet: float64
finishedsquarefeet12: float64
fips: float64
fireplacecnt: float64
garagecarcnt: float64
garagetotalsqft: float64
heatingorsystemtypeid: object
latitude: float64
longitude: float64
lotsizesquarefeet: float64
poolcnt: float64
propertycountylandusecode: object
propertylandusetypeid: float64
propertyzoningdesc: object
rawcensustractandblock: float64
regionidcity: float64
regionidcounty: float64
regionidzip: float64
roomcnt: float64
unitcnt: float64
yearbuilt: float64
numberofstories: float64
structuretaxvaluedollarcnt: float64
taxvaluedollarcnt: float64
assessmentyear: float64
landtaxvaluedollarcnt: float64
taxamount: float64
taxdelinquencyflag: object
censustractandblock: float64

In [80]:
#df.to_csv("cleaned.csv", index = False)